### PR TITLE
Feature/song 231 publish test wiremock

### LINKED ISSUE #231: Add publish test using WireMock

### PR DESCRIPTION
**Pull request by rtisma**
Added WireMock so that the publish endpoint could be tested properly. Also testing publish errors.
Fixes #231

### CODE REVIEW

**Comment by rtisma** [comment]
ok to test

**Comment by rtisma** [comment]
ok to test

**Comment by rtisma** [comment]
ok to test

**Comment by andricDu** [comment]
@rtisma was this the psql issue mentioned at standup?

**Comment by rtisma** [comment]
@andricDu yes it was. I will do #224 which is the jdbi3 upgrade, and see if it fixes this issue.

**Comment by andricDu** [comment]
test this please

**Comment by rtisma** [comment]
ok to test

**Pull request merged**
